name = "EventStudy"
uuid = "187cdbd8-87d9-4782-b53f-d680ff7a9fcd"
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "1.8.1"
Dates = "1.11.0"
Distributions = "0.25.122"
GLM = "1.9.0"
LinearAlgebra = "1.12.0"
NaNStatistics = "0.6.54"
PooledArrays = "1.4.3"
Statistics = "1.11.1"
StatsBase = "0.34.9"
